---
title: Processing Check-in Data for the Analysis of Human Mobility
author:
  # see ?rjournal_article for more information
  - name: Michael Kane
    affiliation: Yale University
    address:
    - 60 College Street
    - New Haven, CT 06510, USA
    email: michael.kane@yale.edu
  - name: Simon Urbanek
    affiliation: The University of Aukland
    address:
    - 38 Princes Street
    - Auckland Central, Aukland 1010, NZ
    email: s.urbanek@auckland.ac.nz
  - name: Owais Gilani
    affiliation: Bucknell Unversity
    address:
    - 38 Princes Street
    - Lewisburgh, PA 17837, USA
    email: owais.gilani@bucknell.edu
abstract: >
  An abstract of less than 150 words.
preamble: |
  % Any extra LaTeX you need in the preamble
  
# per R journal requirement, the bib filename should be the same as the output 
# tex file. Don't forget to rename the bib file and change this example value.
bibliography: RJreferences.bib

output: rticles::rjournal_article
---

# Introduction and Background

Check-in data records the time and location of an electronic device when it is physically in a pre-specified vicinity. While the resolution of the time is generally of order seconds, the resolution of the vicinity can vary greatly depending on the use case. For example, in social media applications user check-ins are often localized to places of interest, like restaurants or concerts having resolutions on the order of meters to hundreds of meters. Other applications, like cell-tower check-ins, which allow cell providers to route calls and data to devices generally have resolutions of tens-of-meters to kilometers, depending on the population density of cell tower usage in the area [@gilani2020].

In addition to differences in physical and temporal resolution there are differences in how the collection of these data is initiated. Social media devices generally rely on user input. That is, users signals they are at location in order to let there connections know and to register the event in their collection of experiences collected by the social media provider. On the other hand, events like cell tower check-ins occur automatically, when users' physical locations change and the move out of range of their current tower and closer to another. In this case the user is ``handed off'' to the closer tower, which is then responsible for delivering data to the device. 

Despite these differences in resolution and record initiation, these types of data can be described similarly both in terms of their structure. 

Note on privacy - intention is to understand aggregate movement. CDC guidelines 9 per census tract

Introductory section which may include references in parentheses
[@R], or cite a reference such as @R in the text.

# Processing tasks for check-in data

## Check-in intervals

## Iterating over time intervals

## Mapping over intervals and groups

## Creating custom interval iterators

# Case Study: Dining patterns in Foursquare data

# Conclusion

# Acknowledgements

This work was partially supported by the National Science Foundation (NSF) Grant Human Networks and Data Science - Infrastructure (HNDS-I), award numbers 2024335 and 2024233.

